### ISSUE TITLE
VERSION file not included on released build v0.2.8

### ISSUE THREAD

**Issue by niedbalski** [Linaro/mr-provisioner#71]
The version file required for the console-entry point (mr-provisioner) and it hasn't been
included as part of the v0.2.8 release file. 

$ virtualenv env -p python3.5 && source env/bin/activate
$ pip install https://github.com/Linaro/mr-provisioner/releases/download/v0.2.8/mr-provisioner-0.2.8.tar.gz
$ mr-provisioner 
Traceback (most recent call last):
  File "/opt/mr-provisioner/venv/bin/mr-provisioner", line 7, in <module>
    from mr_provisioner import main
  File "/opt/mr-provisioner/venv/lib/python3.5/site-packages/mr_provisioner/__init__.py", line 9, in <module>
    from mr_provisioner.config import apply_config
  File "/opt/mr-provisioner/venv/lib/python3.5/site-packages/mr_provisioner/config.py", line 13, in <module>
    version = open(os.path.join(_basedir, 'VERSION')).read().strip()
FileNotFoundError: [Errno 2] No such file or directory: '/opt/mr-provisioner/venv/lib/python3.5/site-packages/VERSION'

**Comment by gemagomez** [comment]
Duplicate of #70.
